---
version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
  
  high_load_app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000

